const cfg=window.SUPABASE_CONFIG||{};
const ready=Boolean(cfg.url&&cfg.anonKey&&window.supabase);
const oauthUsable=ready&&location.protocol!=='file:';
const db=ready?window.supabase.createClient(cfg.url,cfg.anonKey):null;
const login=document.querySelector('#adminLogin'),app=document.querySelector('#adminApp'),content=document.querySelector('#adminContent'),toast=document.querySelector('#adminToast');
let families=[],members=[],tasks=[],activeFamily=null;
function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
async function requireAdmin(){if(!oauthUsable){document.querySelector('#adminAuthStatus').textContent=!ready?'Supabase URL және anon key енгізілмеген':'OAuth үшін сайт http/https адресінде ашылуы керек';document.querySelector('#adminGoogleLogin').disabled=true;return}const {data:{user},error}=await db.auth.getUser();if(error||!user)return;const {data:admin}=await db.from('app_admins').select('user_id').eq('user_id',user.id).maybeSingle();if(!admin){await db.auth.signOut();document.querySelector('#adminAuthStatus').textContent='Бұл аккаунтқа әкімші рұқсаты берілмеген';return}await openAdmin()}
async function openAdmin(){const [f,m,t]=await Promise.all([db.from('families').select('id,name,created_by,created_at'),db.from('family_members').select('family_id,user_id,role'),db.from('tasks').select('id,family_id,status')]);if(f.error||m.error||t.error)return notify('Деректерді жүктеу қатесі');families=f.data||[];members=m.data||[];tasks=t.data||[];login.classList.add('hidden');app.classList.remove('hidden');overview()}
function familyRow(f){const mc=members.filter(m=>m.family_id===f.id).length,tc=tasks.filter(t=>t.family_id===f.id).length;return `<article class="family-row"><div><b>${escapeHtml(f.name)}</b><small>${f.id}</small></div><span>${mc} мүше · ${tc} тапсырма</span><button data-family="${f.id}">Көру</button></article>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
function roleLabel(role){return role==='admin'?'Әкімші':'Мүше'}
function overview(){content.innerHTML=`<div class="stats"><div class="stat"><span>ОТБАСЫЛАР</span><b>${families.length}</b></div><div class="stat"><span>ҚОЛДАНУШЫЛАР</span><b>${members.length}</b></div><div class="stat"><span>БАРЛЫҚ ТАПСЫРМА</span><b>${tasks.length}</b></div><div class="stat"><span>ҚАУІПСІЗДІК</span><b>RLS ✓</b></div></div><div class="panel"><h2>Отбасылық кеңістіктер</h2>${families.map(familyRow).join('')||'<p>Әзірге отбасы жоқ</p>'}</div>`;bindFamilies()}
function bindFamilies(){document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>openFamily(b.dataset.family))}
function showSection(name){document.querySelector('#pageTitle').textContent={overview:'Жалпы шолу',families:'Отбасылар',users:'Қолданушылар',security:'Қауіпсіздік'}[name];if(name==='overview')return overview();if(name==='families'){content.innerHTML=`<div class="panel"><h2>Барлық отбасылар</h2>${families.map(familyRow).join('')}</div>`;return bindFamilies()}if(name==='users'){content.innerHTML=`<div class="panel"><h2>Қолданушылар тізімі</h2>${members.map(m=>`<article class="user-row"><div><b>${m.user_id}</b><small>${m.family_id}</small></div><span>${roleLabel(m.role)}</span></article>`).join('')}</div>`;return}content.innerHTML='<div class="secure-card"><h3>🔒 Дерекқордағы RLS белсенді</h3><p>Әкімші рұқсаты расталған қолданушының ID-і арқылы тексеріледі. Электрондық поштаны өзгертіп, жүйені алдау мүмкін емес.</p><code>public.is_app_admin()</code></div>'}
function openFamily(id){activeFamily=families.find(f=>f.id===id);document.querySelector('#dialogFamily').textContent=activeFamily.name;document.querySelector('#memberList').innerHTML=members.filter(m=>m.family_id===id).map(m=>`<article class="member"><div><b>${m.user_id}</b><small>Расталған қолданушы</small></div><em>${roleLabel(m.role)}</em></article>`).join('');document.querySelector('#membersDialog').showModal()}
document.querySelector('#adminGoogleLogin').onclick=async()=>{if(!oauthUsable)return;localStorage.setItem('uy:adminReturn','1');const redirectTo=new URL('otbasy.html',location.href).href;const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error){localStorage.removeItem('uy:adminReturn');notify(error.message)}};
document.querySelector('#adminLogout').onclick=async()=>{await db.auth.signOut();app.classList.add('hidden');login.classList.remove('hidden')};
document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{document.querySelector('aside nav .active').classList.remove('active');b.classList.add('active');showSection(b.dataset.section)});
document.querySelector('#closeDialog').onclick=()=>document.querySelector('#membersDialog').close();
document.querySelector('#addMemberForm').onsubmit=async e=>{e.preventDefault();const input=document.querySelector('#memberEmail');e.submitter.disabled=true;const{error}=await db.rpc('add_family_member_by_email',{target_family:activeFamily.id,member_email:input.value.trim()});e.submitter.disabled=false;if(error)return notify(error.message.includes('sign in')?'Бұл адам алдымен сайтқа бір рет кіруі керек':'Мүшені қосу мүмкін болмады');input.value='';document.querySelector('#membersDialog').close();await openAdmin();notify('Отбасы мүшесі қосылды')};
requireAdmin();
