const seedTasks = [
  {id:1,title:'Коммуналдық төлемдерді төлеу',day:'today',category:'ҚАРЖЫ',priority:'high',owner:'Д',time:'Бүгін · 18:00',done:false},
  {id:2,title:'Апталық азық-түлік тізімін жасау',day:'today',category:'САТЫП АЛУ',priority:'medium',owner:'А',time:'Бүгін · 19:30',done:false},
  {id:3,title:'Мирастың дәрігеріне жазылу',day:'today',category:'ДЕНСАУЛЫҚ',priority:'high',owner:'Д',time:'Бүгін · 15:00',done:true},
  {id:4,title:'Асүй сөресін реттеу',day:'today',category:'ҮЙ',priority:'low',owner:'М',time:'Бүгін',done:false},
  {id:5,title:'Кітаптарды кітапханаға қайтару',day:'yesterday',category:'ОТБАСЫ',priority:'medium',owner:'А',time:'Кеше · 17:00',done:true},
  {id:6,title:'Демалыс күнін бірге жоспарлау',day:'tomorrow',category:'ОТБАСЫ',priority:'medium',owner:'А',time:'Ертең · 20:00',done:false},
  {id:7,title:'Көлікті техникалық тексеру',day:'week',category:'КӨЛІК',priority:'low',owner:'Д',time:'Осы апта',done:false}
];
const authConfig=window.SUPABASE_CONFIG||{};
const authReady=Boolean(authConfig.url&&authConfig.anonKey&&window.supabase);
const oauthUsable=authReady&&location.protocol!=='file:';
const supabaseClient=authReady?window.supabase.createClient(authConfig.url,authConfig.anonKey):null;
let currentSession=null,tasks=[],comments=[];
let currentDay='today', currentFilter='all', addingToBoard=false;
const list=document.querySelector('#taskList'), dialog=document.querySelector('#taskDialog'), toast=document.querySelector('#toast');
const dayTitles={yesterday:'Кеше не істедік?',today:'Бүгін не істейміз?',tomorrow:'Ертең не істейміз?',week:'Осы аптаның жоспары'};
const priorityText={high:'↑ ЖОҒАРЫ',medium:'— ОРТА',low:'↓ ТӨМЕН'};
const initialBoard={};document.querySelectorAll('.column').forEach(col=>initialBoard[col.dataset.status]=col.querySelector('.board-items').innerHTML);
function familyKey(type){return `uy:${currentSession.familyId}:${type}`}
function taskFromRow(row){const m=row.metadata||{};return{id:row.id,title:row.title,day:m.day||'today',category:m.category||'ОТБАСЫ',priority:row.priority||'medium',owner:m.owner||'Ө',time:m.time||'Жоспарланған',done:row.status==='done'}}
async function loadRemoteTasks(){const{data,error}=await supabaseClient.from('tasks').select('id,title,status,priority,metadata').eq('family_id',currentSession.familyId).order('created_at',{ascending:false});if(error)throw error;tasks=(data||[]).map(taskFromRow)}
function setDynamicDates(){const now=new Date(),days=['Жс','Дс','Сс','Ср','Бс','Жм','Сб'],months=['ҚАҢТАР','АҚПАН','НАУРЫЗ','СӘУІР','МАМЫР','МАУСЫМ','ШІЛДЕ','ТАМЫЗ','ҚЫРКҮЙЕК','ҚАЗАН','ҚАРАША','ЖЕЛТОҚСАН'];const dates=[new Date(now.getFullYear(),now.getMonth(),now.getDate()-1),now,new Date(now.getFullYear(),now.getMonth(),now.getDate()+1)];document.querySelector('#todayLabel').textContent=`${days[now.getDay()].toUpperCase()} · ${now.getDate()} ${months[now.getMonth()]}`;[['yesterday',dates[0]],['today',dates[1]],['tomorrow',dates[2]]].forEach(([key,d])=>{document.querySelector(`#${key}Date`).textContent=String(d.getDate()).padStart(2,'0');document.querySelector(`#${key}Weekday`).textContent=days[d.getDay()]});const start=new Date(now.getFullYear(),0,1),week=Math.ceil((((now-start)/86400000)+start.getDay()+1)/7);document.querySelector('#weekNumber').textContent=`W${week}`}
function render(){
  document.querySelector('#sectionHeading').textContent=dayTitles[currentDay];
  let visible=tasks.filter(t=>currentDay==='week'?['today','tomorrow','week'].includes(t.day):t.day===currentDay);
  if(currentFilter==='open')visible=visible.filter(t=>!t.done); if(currentFilter==='done')visible=visible.filter(t=>t.done);
  list.innerHTML=visible.length?visible.map(t=>`<article class="task ${t.done?'completed':''}" data-id="${t.id}"><button class="check" aria-label="Орындау">✓</button><div><h3>${escapeHtml(t.title)}</h3><div class="task-meta"><span class="category">${t.category}</span><span>${t.time}</span><span class="priority ${t.priority}">${priorityText[t.priority]}</span></div></div><span class="owner">${t.owner}</span></article>`).join(''):`<article class="task"><div>✓</div><div><h3>Бұл күнге тапсырма жоқ</h3><div class="task-meta">Жаңа тапсырма қосуға болады</div></div></article>`;
  list.querySelectorAll('.check').forEach(b=>b.onclick=async()=>{const id=b.closest('.task').dataset.id,task=tasks.find(t=>String(t.id)===id);if(!task)return;const next=!task.done;const{error}=await supabaseClient.from('tasks').update({status:next?'done':'open',metadata:{day:task.day,category:task.category,owner:task.owner,time:task.time,done:next}}).eq('id',id).eq('family_id',currentSession.familyId);if(error)return notify('Тапсырманы жаңарту мүмкін болмады');task.done=next;render();notify(next?'Тамаша! Тапсырма орындалды':'Тапсырма қайта ашылды')});
  const done=tasks.filter(t=>t.done).length;document.querySelector('#doneCount').textContent=done;const pct=tasks.length?Math.min(100,Math.round(done/tasks.length*100)):0;document.querySelector('#weekProgress').style.width=pct+'%';document.querySelector('#score').textContent=pct;
}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function clone(value){return JSON.parse(JSON.stringify(value))}
function resetBoardFor(){document.querySelectorAll('.column').forEach(col=>col.querySelector('.board-items').innerHTML='')}
async function activateSession(account){currentSession=account;await loadRemoteTasks();comments=JSON.parse(localStorage.getItem(familyKey('comments'))||'null')||[];resetBoardFor();loadBoard();document.querySelectorAll('[draggable=true]').forEach(attachDrag);updateBoardCounts();document.querySelector('#authScreen').style.display='none';document.querySelector('#mainApp').classList.remove('auth-hidden');document.querySelector('#profileBtn').textContent=account.name[0];document.querySelector('.greeting h1').innerHTML=`Қайырлы таң,<br><em>${escapeHtml(account.familyName)}.</em>`;currentDay='today';render();notify(`${account.familyName} кеңістігі ашылды`)}
async function loadAuthenticatedUser(user){const name=user.user_metadata?.full_name||user.email?.split('@')[0]||'Қолданушы';let {data,error}=await supabaseClient.from('family_members').select('family_id,role,families(name)').eq('user_id',user.id).limit(1).maybeSingle();if(error)throw error;if(!data){const created=await supabaseClient.rpc('create_family',{family_name:`${name} отбасы`});if(created.error)throw created.error;({data,error}=await supabaseClient.from('family_members').select('family_id,role,families(name)').eq('user_id',user.id).limit(1).single());if(error)throw error}if(localStorage.getItem('uy:adminReturn')==='1'){localStorage.removeItem('uy:adminReturn');location.replace('admin.html');return}const {data:memberRows}=await supabaseClient.from('family_members').select('user_id,role').eq('family_id',data.family_id);await activateSession({id:user.id,name,email:user.email,familyId:data.family_id,familyName:data.families?.name||'Менің отбасым',role:data.role,members:(memberRows||[]).map(m=>[m.user_id===user.id?name:'Отбасы мүшесі',m.user_id,m.role.toUpperCase()])})}
async function initAuth(){document.querySelector('#authScreen').style.display='grid';document.querySelector('#mainApp').classList.add('auth-hidden');if(!oauthUsable){document.querySelector('#authStatus').textContent=!authReady?'Supabase URL және anon key енгізілмеген':'OAuth үшін сайт http/https адресінде ашылуы керек';document.querySelectorAll('[data-provider]').forEach(b=>b.disabled=true);return}try{const {data:{user},error}=await supabaseClient.auth.getUser();if(error)throw error;if(user)await loadAuthenticatedUser(user)}catch(e){document.querySelector('#authStatus').textContent='Кіру қатесі: '+e.message}}
function renderFamily(){const members=JSON.parse(localStorage.getItem(familyKey('members'))||'null')||currentSession.members;document.querySelector('#familyDialog h2').textContent=currentSession.familyName;document.querySelector('.family-list').innerHTML=members.map(m=>`<article><i>${escapeHtml(m[0][0])}</i><div><b>${escapeHtml(m[0])}</b><small>${escapeHtml(m[2])} · ${escapeHtml(m[1])}</small></div></article>`).join('')}
function openDialog(id){const el=document.querySelector('#'+id);el.showModal();return el}
function renderSearch(query=''){const q=query.trim().toLocaleLowerCase('kk');const found=tasks.filter(t=>!q||t.title.toLocaleLowerCase('kk').includes(q));document.querySelector('#searchResults').innerHTML=found.length?found.slice(0,12).map(t=>`<button class="search-result" data-task-id="${t.id}"><b>${escapeHtml(t.title)}</b><small>${t.time} · ${t.done?'Орындалды':'Ашық'}</small></button>`).join(''):'<div class="empty-result">Ештеңе табылмады</div>';document.querySelectorAll('.search-result').forEach(b=>b.onclick=()=>{const task=tasks.find(t=>String(t.id)===b.dataset.taskId);if(!task)return;currentDay=task.day;document.querySelectorAll('.date-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.day===currentDay));document.querySelector('#searchDialog').close();render();document.querySelector('.focus-section').scrollIntoView();notify('Тапсырма табылды')})}
function renderComments(){document.querySelector('#comments').innerHTML=comments.map(c=>`<article class="comment"><b>${escapeHtml(c.author)}</b><p>${escapeHtml(c.text)}</p><small>${escapeHtml(c.time)}</small></article>`).join('')}
document.querySelectorAll('.date-tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.date-tabs .active').classList.remove('active');b.classList.add('active');currentDay=b.dataset.day;render()});
['#addTask','#fab'].forEach(sel=>document.querySelector(sel).onclick=()=>{addingToBoard=false;document.querySelector('#taskDay').value=currentDay==='yesterday'?'today':currentDay;dialog.showModal();setTimeout(()=>document.querySelector('#taskName').focus(),100)});
document.querySelector('#taskForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const name=document.querySelector('#taskName');if(!name.value.trim())return;const owner=document.querySelector('#taskOwner').value,day=document.querySelector('#taskDay').value,priority=document.querySelector('#taskPriority').value,metadata={day,category:'ОТБАСЫ',owner:owner==='Өзім'?currentSession.name[0]:'О',time:'Жаңа',done:false};e.submitter.disabled=true;const{data,error}=await supabaseClient.from('tasks').insert({family_id:currentSession.familyId,title:name.value.trim(),status:'open',priority,created_by:currentSession.id,metadata}).select('id,title,status,priority,metadata').single();e.submitter.disabled=false;if(error)return notify('Тапсырманы сақтау мүмкін болмады');const task=taskFromRow(data);tasks.unshift(task);if(addingToBoard){const card=document.createElement('article');card.draggable=true;card.dataset.id='b'+task.id;card.innerHTML=`<small>ИДЕЯ</small><h4>${escapeHtml(task.title)}</h4><footer><span class="priority ${priority}">${priorityText[priority]}</span><i>${metadata.owner}</i></footer>`;document.querySelector('.column[data-status="backlog"] .board-items').prepend(card);attachDrag(card);updateBoardCounts();saveBoard()}dialog.close();name.value='';currentDay=day;document.querySelectorAll('.date-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.day===currentDay));render();notify(addingToBoard?'Идея backlog-қа қосылды':'Жаңа тапсырма қосылды');addingToBoard=false});
document.querySelector('#filterBtn').onclick=e=>{const states=[['all','Барлығы'],['open','Ашық'],['done','Орындалды']];let i=states.findIndex(s=>s[0]===currentFilter);[currentFilter,e.currentTarget.childNodes[0].textContent]=[states[(i+1)%3][0],states[(i+1)%3][1]+' '];render()};
document.querySelector('#solveBtn').onclick=()=>{renderComments();openDialog('discussionDialog')};
document.querySelector('#searchBtn').onclick=()=>{renderSearch();openDialog('searchDialog');setTimeout(()=>document.querySelector('#searchInput').focus(),80)};
document.querySelector('#profileBtn').onclick=()=>{renderFamily();openDialog('familyDialog')};document.querySelector('#allProblemsBtn').onclick=()=>{renderComments();openDialog('discussionDialog')};
document.querySelector('#searchInput').oninput=e=>renderSearch(e.target.value);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.close).close());
document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=async()=>{if(!oauthUsable)return;const provider=b.dataset.provider==='apple'?'apple':'google';const redirectTo=new URL('otbasy.html',location.href).href;const {error}=await supabaseClient.auth.signInWithOAuth({provider,options:{redirectTo}});if(error)document.querySelector('#authStatus').textContent='Кіру қатесі: '+error.message});
document.querySelector('#userLogout').onclick=async()=>{await supabaseClient.auth.signOut();currentSession=null;tasks=[];comments=[];document.querySelector('#familyDialog').close();initAuth()};
document.querySelector('#commentForm').onsubmit=e=>{e.preventDefault();const input=document.querySelector('#commentInput');comments.push({author:currentSession.name,text:input.value.trim(),time:'Қазір'});localStorage.setItem(familyKey('comments'),JSON.stringify(comments));input.value='';renderComments();notify('Пікір қосылды')};
document.querySelectorAll('.bottom-nav button[data-nav]').forEach(b=>b.onclick=()=>{document.querySelector('.bottom-nav .active')?.classList.remove('active');b.classList.add('active');if(b.dataset.nav==='sprint')document.querySelector('.sprint-section').scrollIntoView();else if(b.dataset.nav==='plan')document.querySelector('.focus-section').scrollIntoView();else if(b.dataset.nav==='family'){renderFamily();openDialog('familyDialog')}else window.scrollTo({top:0,behavior:'smooth'})});
function updateBoardCounts(){let total=0,done=0;document.querySelectorAll('.column').forEach(col=>{const count=col.querySelectorAll('.board-items article').length;col.querySelector('header b').textContent=count;total+=count;if(col.dataset.status==='done')done=count});document.querySelector('.sprint-stat b').textContent=`${done} / ${total}`}
function saveBoard(){const state={};document.querySelectorAll('.column').forEach(col=>state[col.dataset.status]=col.querySelector('.board-items').innerHTML);localStorage.setItem(familyKey('board'),JSON.stringify(state))}
function loadBoard(){const boardState=JSON.parse(localStorage.getItem(familyKey('board'))||'null');if(boardState)Object.entries(boardState).forEach(([status,html])=>{const container=document.querySelector(`.column[data-status="${status}"] .board-items`);if(container&&typeof html==='string')container.innerHTML=html})}
let dragged;function attachDrag(card){card.addEventListener('dragstart',()=>dragged=card)}document.querySelectorAll('[draggable=true]').forEach(attachDrag);document.querySelectorAll('.column').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('dragover')});col.addEventListener('dragleave',()=>col.classList.remove('dragover'));col.addEventListener('drop',()=>{col.classList.remove('dragover');if(dragged){col.querySelector('.board-items').appendChild(dragged);updateBoardCounts();saveBoard();dragged=null;notify('Тапсырма мәртебесі жаңарды')}})});
document.querySelector('.column-add').onclick=()=>{addingToBoard=true;dialog.showModal();document.querySelector('#taskDay').value='week';setTimeout(()=>document.querySelector('#taskName').focus(),80)};
setDynamicDates();initAuth();
